server:
  port: 8082
spring:
  application:
    name: order-service

# URL base do catalog-service; em produção isso viria de Discover/Gateway/Config servidor
catalog:
  base-url: http://localhost:8081

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info
